#!/home/klab/venv/bin/python
from joblib import Parallel, delayed
import itertools
import os


cmds = [
    'python3 main.py --solver=ts --save_trace --headless',
]
expected_n_events = [6, 7, 8, 9, 10]

new_cmds = []
for expected_n_event, cmd in itertools.product(expected_n_events, cmds):
    new_cmds.append(cmd + f' --expected_n_event={expected_n_event}')
cmds = new_cmds

def f(cmd):
    print(f'[+] executing: {cmd}')
    os.system(cmd)

Parallel(n_jobs=os.cpu_count())(delayed(f)(cmd) for cmd in cmds)
